import type { Metadata } from "next"
import Link from "next/link"
import { notFound } from "next/navigation"
import { ArrowLeft, ArrowRight } from "lucide-react"

import { getDocMeta, getDocNeighbours, getDocSlugs, loadDoc } from "@/lib/docs"
import { getDictionary } from "@/lib/i18n/dictionaries"
import { isLocale, localePath } from "@/lib/i18n/config"
import { pageMetadata } from "@/lib/seo"

interface PageProps {
  params: Promise<{ lang: string; slug: string }>
}

// Slug lists are identical across locales; this runs once per [lang] param
// generated by the parent [lang] layout.
export async function generateStaticParams() {
  return getDocSlugs("en").map((slug) => ({ slug }))
}

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { lang, slug } = await params
  if (!isLocale(lang)) notFound()
  const meta = getDocMeta(lang, slug)
  if (!meta) notFound()
  return pageMetadata({
    locale: lang,
    path: `model/${slug}`,
    title: meta.title,
    description: meta.description,
  })
}

export default async function DocChapterPage({ params }: PageProps) {
  const { lang, slug } = await params
  if (!isLocale(lang)) notFound()

  const meta = getDocMeta(lang, slug)
  const Content = loadDoc(lang, slug)
  if (!meta || !Content) notFound()

  const dict = getDictionary(lang)
  const { prev, next } = getDocNeighbours(lang, slug)

  return (
    <article className="mx-auto max-w-3xl">
      <header className="pb-10">
        <span className="inline-flex items-center gap-1.5 rounded-full border px-3 py-1 text-xs font-medium text-muted-foreground">
          <span aria-hidden="true" className="size-1.5 rounded-full bg-gold" />
          {dict.docs.label}
        </span>
        <h1 className="mt-4 text-balance text-3xl font-semibold tracking-tight sm:text-4xl">
          {meta.title}
        </h1>
        {meta.description ? (
          <p className="mt-4 text-pretty text-sm leading-relaxed text-muted-foreground sm:text-base">
            {meta.description}
          </p>
        ) : null}
      </header>

      <div className="prose prose-neutral dark:prose-invert max-w-none prose-headings:tracking-tight prose-a:font-medium prose-a:text-primary prose-a:no-underline hover:prose-a:underline">
        <Content />
      </div>

      <nav
        aria-label={dict.docs.sidebarTitle}
        className="mt-16 flex flex-col gap-3 border-t border-border/60 pt-8 sm:flex-row sm:justify-between"
      >
        {prev ? (
          <Link
            href={localePath(lang, `model/${prev.slug}`)}
            className="group flex items-center gap-2 rounded-lg border border-border/60 px-4 py-3 text-sm transition-colors outline-none hover:bg-muted/50 focus-visible:ring-2 focus-visible:ring-ring/40"
          >
            <ArrowLeft className="size-4 shrink-0 text-muted-foreground transition-transform group-hover:-translate-x-0.5" />
            <span className="min-w-0 truncate font-medium">{prev.title}</span>
          </Link>
        ) : (
          <span className="hidden sm:block" />
        )}
        {next ? (
          <Link
            href={localePath(lang, `model/${next.slug}`)}
            className="group flex items-center justify-between gap-2 rounded-lg border border-border/60 px-4 py-3 text-sm transition-colors outline-none hover:bg-muted/50 focus-visible:ring-2 focus-visible:ring-ring/40 sm:justify-end sm:text-right"
          >
            <span className="min-w-0 truncate font-medium">{next.title}</span>
            <ArrowRight className="size-4 shrink-0 text-muted-foreground transition-transform group-hover:translate-x-0.5" />
          </Link>
        ) : (
          <span className="hidden sm:block" />
        )}
      </nav>
    </article>
  )
}
